language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest

notifications:
  email: false